In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from scipy import signal 
import warnings 

warnings.filterwarnings("ignore") 
plt.rcParams['figure.figsize'] = (12, 6) 
plt.rcParams['axes.grid'] = True

In [3]:
df=pd.read_csv('../signal_processing/IQ Raw Data of Continuous Wave Radar 24 GHz ViRa Sykno.csv')
df.head()

,# Created with Sykno's ViRa24,UI version 1.0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,# Start time: 2025-05-23 09-54-56,NaN,NaN,NaN,NaN,NaN
1,# Format: I,Q,ECG1,ECG2,ANA1,ANA2
2,# Sample rate: 1000 Sa/s,NaN,NaN,NaN,NaN,NaN
3,-117974,-1424541,2162,2045,-29066,-33862
4,-117955,-1424235,2148,2042,-29067,-33861

In [5]:
df.shape

(60009, 6)

In [7]:
df.describe()

,# Created with Sykno's ViRa24,UI version 1.0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
count,60009,60007,60007,60007,60007,60007
unique,54296,54449,69,66,193,195
top,-57266,-1263530,2148,2038,-29074,-33859
freq,5,6,3562,3638,1040,1022

In [8]:
df.isnull().sum()

# Created with Sykno's ViRa24    0
 UI version 1.0                  2
Unnamed: 2                       2
Unnamed: 3                       2
Unnamed: 4                       2
Unnamed: 5                       2
dtype: int64

In [10]:
df.duplicated().sum()

0

In [11]:
fs = 1000  # Sampling frequency
N=len(df)  # Number of samples 
duration = N/fs  # Duration in seconds 

print(f"Number of samples: {N}") 
print(f"Duration: {duration} seconds") 
print(f"Sampling frequency: {fs} Hz") 
print(f"Time between samples: {1/fs} seconds") 
print(f"Total duration: {N/fs} seconds")

Number of samples: 60009
Duration: 60.009 seconds
Sampling frequency: 1000 Hz
Time between samples: 0.001 seconds
Total duration: 60.009 seconds

In [13]:
time= np.arange(len(df))/fs  # Time vector 
df['time'] = time  # Add time column to dataframe 
df

,# Created with Sykno's ViRa24,UI version 1.0,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,time
0,# Start time: 2025-05-23 09-54-56,NaN,NaN,NaN,NaN,NaN,0.000
1,# Format: I,Q,ECG1,ECG2,ANA1,ANA2,0.001
2,# Sample rate: 1000 Sa/s,NaN,NaN,NaN,NaN,NaN,0.002
3,-117974,-1424541,2162,2045,-29066,-33862,0.003
4,-117955,-1424235,2148,2042,-29067,-33861,0.004
...,...,...,...,...,...,...,...
60004,-132227,-1403638,2143,2039,-29151,-33906,60.004
60005,-131901,-1404240,2138,2054,-29146,-33894,60.005
60006,-131508,-1404821,2131,2035,-29139,-33899,60.006
60007,-131064,-1405304,2127,2019,-29144,-33897,60.007
60008,-130696,-1405781,2145,2028,-29143,-33905,60.008

In [ ]:
channels=['I', 'Q','ECG1','ECG2','ANA1', 'ANA2']  
# List of channel names
fig,axes=plt.subplots(len(channels),1,sharex=True)